### ISSUE TITLE
Unable to view image gallery when selecting a source

### ISSUE THREAD

**Issue by jorgedavila25** [imgix/contentful#111]
**Describe the bug**
Unable to view image gallery when selecting a source

**To Reproduce**
- Fire up the Contentful plug in
- Select Source
- Verify that photos aren't showing up

**Expected behavior**
We should be able to browse and select photos when having a source selected. 

**Screenshots/Videos**

https://www.loom.com/share/b9bacc5854c0404f9eb126ddb71b6993

**Information:**
 - @imgix/contentful version: 1.2.0

**Additional context**

We started to experience this behavior at the same time 1.2.0 was released (adding asset metadata to returned JSON object)

I'm also seeing this error on the console when selecting a source: 

<img width="1728" alt="Screen Shot 2022-02-01 at 11 18 46 AM" src="https://user-images.githubusercontent.com/1642247/152017676-6e049726-1eca-41fd-b2f5-a34ce4cbb6c0.png">

**Comment by sherwinski** [comment]
Hey @jorgedavila25, thanks for providing more information here. A PR (#112) has been opened to fix this issue.

**Comment by jorgedavila25** [comment]
Thanks @sherwinski for getting on this so quickly! Will close out
