### ISSUE TITLE
Timeline for release

### ISSUE THREAD

**Issue by TimonVS** [imgix/contentful#12]
Hi! We just noticed this app, we're excited to use it in our Contentful projects. I was wondering if you could shed some light on the release timeline of this app?

**Comment by sherwinski** [comment]
Hey @TimonVS 👋 
Glad to hear you're excited about using this app. Our current timeline is to have the initial release around the end of April.

**Comment by TimonVS** [comment]
Thanks so much! For now we can put Imgix in front of Contentful’s CDN.

**Comment by sherwinski** [comment]
Glad to hear it! I'm going to close this issue for now, but I'll be sure to comment here with any updates.

**Comment by sherwinski** [comment]
Ah no worries then, thanks for letting me know 👍
