### ISSUE TITLE
Server / Validation error when selecting image in Contentful

### ISSUE THREAD

**Issue by fedorish** [imgix/contentful#83]
Please provide the following information and someone from @imgix/imgix-sdk-team will respond to your issue shortly.

**Before you submit:**

- [x] Please search through the [existing issues](https://github.com/imgix/contentful/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your question has already been discussed.

**Question**
A clear and concise description of your question.

Hey, really appreciated that you've taken the time to created this app. It was easy to install the app in contenful. I do have one issue though that I can't figure out why I'm having. If you look at the attached picture you can see I get some errors in contentful when I have selected my image. 

I've re-installed app and tried different settings, read the docs, but I can't seem to figure it out. I don't even know if it's contentful or something wrong with my app-config. But if you have some ideas of what could be wrong I would really appreciate any help.

Thanks again for the app!

![image](https://user-images.githubusercontent.com/22777727/135767699-80df6ae5-16a4-40fa-ad2b-cea2289bd34a.png)

**Comment by sherwinski** [comment]
Hey @fedorish, thanks for the question and glad you like the app!

I have some suspicions of what it might be but I'll need a bit more information from you in order to be sure. If you don't mind, could you share with me:

- The console output in your browser's developer tools when this error occurs
- A screenshot of your instance's app definition 
<img width="693" alt="Screen Shot 2021-10-04 at 1 42 39 PM" src="https://user-images.githubusercontent.com/15919091/135898610-d16c87a1-99b6-46b3-9e0e-9c26f2ffe8f0.png">

- What is the content type of the field in question (ie `Tes`) that is throwing this error
- When did you (roughly) clone/install this app into your Contentful dashboard?

I should also warn that this app is still in active development so it's possible that we made a change at some point between now and when you installed it that is causing this issue. The good news is that I can tell you that we will have a stable release for this project very soon.

**Comment by fedorish** [comment]
> Hey @fedorish, thanks for the question and glad you like the app!
> 
> I have some suspicions of what it might be but I'll need a bit more information from you in order to be sure. If you don't mind, could you share with me:
> 
> * The console output in your browser's developer tools when this error occurs
> * A screenshot of your instance's app definition
> 
> <img alt="Screen Shot 2021-10-04 at 1 42 39 PM" width="693" src="https://user-images.githubusercontent.com/15919091/135898610-d16c87a1-99b6-46b3-9e0e-9c26f2ffe8f0.png">
> 
> * What is the content type of the field in question (ie `Tes`) that is throwing this error
> * When did you (roughly) clone/install this app into your Contentful dashboard?
> 
> I should also warn that this app is still in active development so it's possible that we made a change at some point between now and when you installed it that is causing this issue. The good news is that I can tell you that we will have a stable release for this project very soon.


**Console log :** 
Points me to this error: 

**App definition:** 
Been playing around with some different settings trying to get it to work, but this is the current one
![image](https://user-images.githubusercontent.com/22777727/135920945-94bbc60e-6806-4fdb-a805-1adf83489eb4.png)

** Content type:**
It's a media with the default settings, but the the `Appearance` is the to "Imgix Integration" instead of `Asset Card (Default)`.

** Install date: ** 
It was this weekend, saturday morning I think.

**Comment by sherwinski** [comment]
Ah I see the problem. The short answer here is that the app can only be rendered in a field of type `JSON object`.

<img width="861" alt="Screen Shot 2021-10-05 at 11 20 48 AM" src="https://user-images.githubusercontent.com/15919091/136052786-b0654068-0b90-430b-be47-ff1b50811d90.png">

Hopefully that solves it for you! I'll be sure to highlight this detail in the project documentation so it's more clear in the future.

**Comment by fedorish** [comment]
> Ah I see the problem. The short answer here is that the app can only be rendered in a field of type `JSON object`.
> 
> <img alt="Screen Shot 2021-10-05 at 11 20 48 AM" width="861" src="https://user-images.githubusercontent.com/15919091/136052786-b0654068-0b90-430b-be47-ff1b50811d90.png">
> 
> Hopefully that solves it for you! I'll be sure to highlight this detail in the project documentation so it's more clear in the future.

Thanks, that did it! Closing this. 

Do Imgix allow file upload via API so that a possible feature would be uploading images to Imgix (and through imgix  to the storage like S3) via media upload  in contentful?

**Comment by sherwinski** [comment]
Glad that worked 👍 

> Do Imgix allow file upload via API so that a possible feature would be uploading images to Imgix (and through imgix to the storage like S3) via media upload in contentful?

That is not a feature that is currently supported by this app but is certainly something we can consider in future iterations.
